import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/context";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config/wagmiConfig";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en" theme="dark" >
        <body className={inter.className}>
          <Provider initialState={initialState}>{children}</Provider>
        </body>
      </html>
  );
}
